import type {
  Attachment,
  Conversation,
  DemoState,
  Friend,
  Message,
  Notification,
  Settings,
  Story,
  User,
} from "./types";

const avatar = (id: number) => `https://i.pravatar.cc/160?img=${id}`;

function makeUser(
  id: string,
  name: string,
  username: string,
  initials: string,
  avatarUrl: string,
  status: User["status"],
  lastSeen: string,
  bio: string,
  location: string,
  email: string,
  phone: string,
  website: string,
  joinedAt: string,
): User {
  return {
    id,
    name,
    username,
    initials,
    avatar: avatarUrl,
    status,
    lastSeen,
    bio,
    location,
    email,
    phone,
    website,
    joinedAt,
  };
}

const users = {
  me: makeUser(
    "me",
    "Kritartha Parasar",
    "@kritartha",
    "KP",
    avatar(12),
    "online",
    "Active now",
    "Student · Coder · Editor · Anime Lover",
    "San Francisco, CA",
    "kritartha@nexus.chat",
    "+1 (415) 555-0128",
    "kritartha.dev",
    "12 Apr 2008",
  ),
  sofia: makeUser(
    "sofia",
    "Sofia Chen",
    "@sofiachen",
    "SC",
    avatar(47),
    "online",
    "Active now",
    "UI/UX Designer · Content Creator · Anime Lover",
    "San Francisco, CA",
    "sofia@nexus.chat",
    "+1 (415) 555-0184",
    "sofia.design",
    "12 Apr 2022",
  ),
  marcus: makeUser(
    "marcus",
    "Marcus Webb",
    "@marcusw",
    "MW",
    avatar(11),
    "away",
    "Away · 18m",
    "Product builder and weekend photographer.",
    "Brooklyn, NY",
    "marcus@nexus.chat",
    "+1 (718) 555-0141",
    "marcus.builds",
    "24 Sep 2021",
  ),
  priya: makeUser(
    "priya",
    "Priya Sharma",
    "@priyasharma",
    "PS",
    avatar(32),
    "online",
    "Active now",
    "Growth strategist, plant collector, and curious human.",
    "Austin, TX",
    "priya@nexus.chat",
    "+1 (512) 555-0176",
    "priya.growth",
    "03 Jun 2023",
  ),
  elena: makeUser(
    "elena",
    "Elena Vasquez",
    "@elena.v",
    "EV",
    avatar(44),
    "offline",
    "Last active yesterday",
    "Community lead building kinder corners of the internet.",
    "Madrid, ES",
    "elena@nexus.chat",
    "+34 91 555 0162",
    "elena.community",
    "18 Jan 2024",
  ),
  aisha: makeUser(
    "aisha",
    "Aisha Patel",
    "@aishap",
    "AP",
    avatar(25),
    "away",
    "Away · 2h",
    "Data storyteller and calm systems thinker.",
    "London, UK",
    "aisha@nexus.chat",
    "+44 20 5555 0139",
    "aisha.codes",
    "09 Nov 2022",
  ),
  nina: makeUser(
    "nina",
    "Nina Rao",
    "@nina.rao",
    "NR",
    avatar(5),
    "online",
    "Active now",
    "Illustrator, mentor, and iced coffee enthusiast.",
    "Toronto, CA",
    "nina@nexus.chat",
    "+1 (416) 555-0105",
    "nina.illustrates",
    "29 Jul 2020",
  ),
};

const attachment = (
  name: string,
  type: string,
  size: number,
  kind: Attachment["kind"],
  previewUrl = "",
): Attachment => ({
  id: `${name}-${size}`,
  name,
  type,
  size,
  kind,
  url: "",
  previewUrl,
  progress: 100,
});

function makeMessage(
  conversationId: string,
  author: User,
  text: string,
  createdAt: string,
  options: {
    status?: Message["status"];
    attachments?: Attachment[];
    replyToId?: string | null;
    reactions?: Record<string, string[]>;
    edited?: boolean;
    pinned?: boolean;
  } = {},
): Message {
  return {
    id: `${conversationId}-${createdAt}-${author.id}`,
    conversationId,
    authorId: author.id,
    authorName: author.name,
    authorInitials: author.initials,
    authorAvatar: author.avatar,
    text,
    createdAt,
    status: options.status ?? "read",
    attachments: options.attachments ?? [],
    replyToId: options.replyToId ?? null,
    reactions: options.reactions ?? {},
    edited: options.edited ?? false,
    pinned: options.pinned ?? false,
    deleted: false,
  };
}

function createConversations(): Conversation[] {
  return [
    {
      id: "sofia",
      kind: "direct",
      name: users.sofia.name,
      initials: users.sofia.initials,
      avatar: users.sofia.avatar,
      status: users.sofia.status,
      lastSeen: users.sofia.lastSeen,
      unread: 3,
      pinned: true,
      muted: false,
      archived: false,
      typing: false,
      memberIds: ["me", "sofia"],
      groupDescription: "Design friends",
      messages: [
        makeMessage(
          "sofia",
          users.sofia,
          "Hey! Did you see the new design I sent?",
          "2026-09-28T10:42:00.000Z",
        ),
        makeMessage("sofia", users.me, "Yeah! It looks amazing. 🔥", "2026-09-28T10:43:00.000Z", {
          status: "read",
        }),
        makeMessage(
          "sofia",
          users.sofia,
          "Can you check the updated files?",
          "2026-09-28T10:44:00.000Z",
          {
            attachments: [attachment("UI_Design_Final.pdf", "application/pdf", 2400000, "file")],
          },
        ),
        makeMessage("sofia", users.me, "Sure! Give me a few minutes.", "2026-09-28T10:45:00.000Z", {
          status: "read",
        }),
        makeMessage(
          "sofia",
          users.sofia,
          "Also, what do you think about this version?",
          "2026-09-28T10:46:00.000Z",
          {
            attachments: [
              attachment(
                "nexus-lake.jpg",
                "image/jpeg",
                860000,
                "image",
                "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=900&q=80",
              ),
            ],
            reactions: { "❤️": ["me", "sofia"] },
          },
        ),
        makeMessage("sofia", users.me, "This looks insane! 😍", "2026-09-28T10:47:00.000Z", {
          status: "read",
        }),
        makeMessage(
          "sofia",
          users.sofia,
          "Glad you like it! Let's push it today 🚀",
          "2026-09-28T10:48:00.000Z",
        ),
        makeMessage(
          "sofia",
          users.me,
          "Perfect! I’ll handle the deployment.",
          "2026-09-28T10:49:00.000Z",
          { status: "read" },
        ),
      ],
    },
    {
      id: "design-squad",
      kind: "group",
      name: "Design Squad",
      initials: "DS",
      avatar: avatar(49),
      status: "online",
      lastSeen: "4 members online",
      unread: 12,
      pinned: true,
      muted: false,
      archived: false,
      typing: true,
      memberIds: ["me", "sofia", "priya", "nina"],
      groupDescription: "Ship thoughtful work together.",
      messages: [
        makeMessage(
          "design-squad",
          users.priya,
          "Just pushed the new components 🚀",
          "2026-09-28T10:31:00.000Z",
        ),
        makeMessage(
          "design-squad",
          users.sofia,
          "The spacing pass is looking so much cleaner.",
          "2026-09-28T10:32:00.000Z",
        ),
        makeMessage(
          "design-squad",
          users.me,
          "I’ll wire the interaction states next.",
          "2026-09-28T10:33:00.000Z",
          { status: "read" },
        ),
      ],
    },
    {
      id: "marcus",
      kind: "direct",
      name: users.marcus.name,
      initials: users.marcus.initials,
      avatar: users.marcus.avatar,
      status: users.marcus.status,
      lastSeen: users.marcus.lastSeen,
      unread: 0,
      pinned: false,
      muted: false,
      archived: false,
      typing: false,
      memberIds: ["me", "marcus"],
      groupDescription: "Direct conversation",
      messages: [
        makeMessage(
          "marcus",
          users.marcus,
          "Sounds good, let’s catch up tomorrow",
          "2026-09-28T09:15:00.000Z",
        ),
        makeMessage(
          "marcus",
          users.me,
          "Absolutely. I’ll send a time later today.",
          "2026-09-28T09:18:00.000Z",
          { status: "read" },
        ),
      ],
    },
    {
      id: "priya",
      kind: "direct",
      name: users.priya.name,
      initials: users.priya.initials,
      avatar: users.priya.avatar,
      status: users.priya.status,
      lastSeen: users.priya.lastSeen,
      unread: 1,
      pinned: false,
      muted: false,
      archived: false,
      typing: false,
      memberIds: ["me", "priya"],
      groupDescription: "Direct conversation",
      messages: [
        makeMessage("priya", users.priya, "Photo", "2026-09-27T16:20:00.000Z", {
          attachments: [
            attachment(
              "weekend-photo.jpg",
              "image/jpeg",
              540000,
              "image",
              "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=80",
            ),
          ],
        }),
      ],
    },
    {
      id: "weekend-warriors",
      kind: "group",
      name: "Weekend Warriors",
      initials: "WW",
      avatar: avatar(36),
      status: "online",
      lastSeen: "8 members online",
      unread: 0,
      pinned: false,
      muted: true,
      archived: false,
      typing: false,
      memberIds: ["me", "marcus", "priya", "nina"],
      groupDescription: "Saturday works for everyone?",
      messages: [
        makeMessage(
          "weekend-warriors",
          users.marcus,
          "Saturday works for everyone?",
          "2026-09-27T12:00:00.000Z",
        ),
        makeMessage("weekend-warriors", users.me, "Count me in 🌄", "2026-09-27T12:04:00.000Z", {
          status: "read",
        }),
      ],
    },
    {
      id: "nexus-team",
      kind: "group",
      name: "Nexus Team",
      initials: "NX",
      avatar: "",
      status: "online",
      lastSeen: "12 members online",
      unread: 2,
      pinned: false,
      muted: false,
      archived: false,
      typing: false,
      memberIds: ["me", "sofia", "marcus", "priya"],
      groupDescription: "Product updates and launch notes.",
      messages: [
        makeMessage(
          "nexus-team",
          users.sofia,
          "New update is live! 🚀",
          "2026-09-27T09:15:00.000Z",
        ),
        makeMessage("nexus-team", users.me, "Amazing work everyone.", "2026-09-27T09:20:00.000Z", {
          status: "read",
        }),
      ],
    },
    {
      id: "anime-squad",
      kind: "group",
      name: "Anime Squad",
      initials: "AS",
      avatar: avatar(13),
      status: "online",
      lastSeen: "22 members online",
      unread: 0,
      pinned: false,
      muted: false,
      archived: false,
      typing: false,
      memberIds: ["me", "sofia", "nina"],
      groupDescription: "Recommendations, watch parties, and art.",
      messages: [
        makeMessage("anime-squad", users.nina, "Kiyo: That’s amazing!", "2026-09-26T19:10:00.000Z"),
        makeMessage(
          "anime-squad",
          users.me,
          "The new season is looking great.",
          "2026-09-26T19:14:00.000Z",
          { status: "read" },
        ),
      ],
    },
    {
      id: "study-group",
      kind: "group",
      name: "Study Group",
      initials: "SG",
      avatar: avatar(19),
      status: "away",
      lastSeen: "567 members",
      unread: 0,
      pinned: false,
      muted: false,
      archived: true,
      typing: false,
      memberIds: ["me", "aisha", "elena"],
      groupDescription: "Notes and accountability.",
      messages: [
        makeMessage("study-group", users.aisha, "Notes.pdf", "2026-09-25T13:00:00.000Z", {
          attachments: [attachment("Notes.pdf", "application/pdf", 2100000, "file")],
        }),
      ],
    },
    {
      id: "gaming-hub",
      kind: "group",
      name: "Gaming Hub",
      initials: "GH",
      avatar: avatar(8),
      status: "online",
      lastSeen: "2,341 members",
      unread: 0,
      pinned: false,
      muted: false,
      archived: false,
      typing: false,
      memberIds: ["me", "marcus", "nina"],
      groupDescription: "Let’s play tonight?",
      messages: [
        makeMessage("gaming-hub", users.marcus, "Let’s play tonight?", "2026-09-24T18:00:00.000Z"),
      ],
    },
  ];
}

function createFriends(): Friend[] {
  return [
    {
      id: "sofia",
      name: users.sofia.name,
      username: users.sofia.username,
      initials: users.sofia.initials,
      avatar: users.sofia.avatar,
      status: users.sofia.status,
      lastSeen: users.sofia.lastSeen,
      state: "accepted",
      mutualGroups: 4,
    },
    {
      id: "marcus",
      name: users.marcus.name,
      username: users.marcus.username,
      initials: users.marcus.initials,
      avatar: users.marcus.avatar,
      status: users.marcus.status,
      lastSeen: users.marcus.lastSeen,
      state: "accepted",
      mutualGroups: 2,
    },
    {
      id: "priya",
      name: users.priya.name,
      username: users.priya.username,
      initials: users.priya.initials,
      avatar: users.priya.avatar,
      status: users.priya.status,
      lastSeen: users.priya.lastSeen,
      state: "accepted",
      mutualGroups: 5,
    },
    {
      id: "nina",
      name: users.nina.name,
      username: users.nina.username,
      initials: users.nina.initials,
      avatar: users.nina.avatar,
      status: users.nina.status,
      lastSeen: users.nina.lastSeen,
      state: "accepted",
      mutualGroups: 1,
    },
    {
      id: "elena",
      name: users.elena.name,
      username: users.elena.username,
      initials: users.elena.initials,
      avatar: users.elena.avatar,
      status: users.elena.status,
      lastSeen: users.elena.lastSeen,
      state: "pending-incoming",
      mutualGroups: 3,
    },
    {
      id: "aisha",
      name: users.aisha.name,
      username: users.aisha.username,
      initials: users.aisha.initials,
      avatar: users.aisha.avatar,
      status: users.aisha.status,
      lastSeen: users.aisha.lastSeen,
      state: "pending-outgoing",
      mutualGroups: 1,
    },
  ];
}

function createNotifications(): Notification[] {
  return [
    {
      id: "notification-1",
      type: "message",
      title: "New message from Sofia",
      description: "Can you check the updated files?",
      createdAt: "2026-09-28T10:44:00.000Z",
      read: false,
      initials: users.sofia.initials,
      avatar: users.sofia.avatar,
    },
    {
      id: "notification-2",
      type: "friend-request",
      title: "Elena sent you a friend request",
      description: "You have 3 mutual groups.",
      createdAt: "2026-09-28T09:30:00.000Z",
      read: false,
      initials: users.elena.initials,
      avatar: users.elena.avatar,
    },
    {
      id: "notification-3",
      type: "mention",
      title: "You were mentioned in Design Squad",
      description: "Priya: Kritartha, can you review the states?",
      createdAt: "2026-09-27T16:42:00.000Z",
      read: true,
      initials: "DS",
      avatar: avatar(49),
    },
    {
      id: "notification-4",
      type: "group-activity",
      title: "Nexus Team shared a new update",
      description: "The new release notes are ready.",
      createdAt: "2026-09-27T09:15:00.000Z",
      read: true,
      initials: "NX",
      avatar: "",
    },
  ];
}

function createStories(): Story[] {
  return [
    {
      id: "story-me",
      authorId: "me",
      name: "Your status",
      initials: users.me.initials,
      avatar: users.me.avatar,
      kind: "text",
      content: "Building something bright ✨",
      image: "",
      createdAt: "2026-09-28T08:00:00.000Z",
      expiresAt: "2026-09-29T08:00:00.000Z",
      viewed: true,
    },
    {
      id: "story-sofia",
      authorId: "sofia",
      name: users.sofia.name,
      initials: users.sofia.initials,
      avatar: users.sofia.avatar,
      kind: "image",
      content: "Moodboard morning",
      image:
        "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=500&q=80",
      createdAt: "2026-09-28T07:20:00.000Z",
      expiresAt: "2026-09-29T07:20:00.000Z",
      viewed: false,
    },
    {
      id: "story-priya",
      authorId: "priya",
      name: users.priya.name,
      initials: users.priya.initials,
      kind: "text",
      content: "Small wins count.",
      image: "",
      avatar: users.priya.avatar,
      createdAt: "2026-09-27T18:00:00.000Z",
      expiresAt: "2026-09-28T18:00:00.000Z",
      viewed: true,
    },
    {
      id: "story-nina",
      authorId: "nina",
      name: users.nina.name,
      initials: users.nina.initials,
      avatar: users.nina.avatar,
      kind: "image",
      content: "Sketchbook",
      image:
        "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=500&q=80",
      createdAt: "2026-09-27T16:00:00.000Z",
      expiresAt: "2026-09-28T16:00:00.000Z",
      viewed: false,
    },
  ];
}

const settings: Settings = {
  theme: "dark",
  notifications: true,
  sounds: true,
  compactMode: false,
  readReceipts: true,
  onlineStatus: true,
  demoMode: true,
};

export function createSeedState(): DemoState {
  return {
    currentUser: { ...users.me },
    conversations: createConversations(),
    friends: createFriends(),
    notifications: createNotifications(),
    stories: createStories(),
    recentSearches: ["Sofia Chen", "Design Squad", "Weekend plans"],
    settings: { ...settings },
    session: {
      authenticated: true,
      email: users.me.email,
      pendingEmail: "",
      verificationCode: "258146",
    },
  };
}

export const conversations = createConversations();
